---
certbot_create_if_missing: yes
certbot_create_command: "{{ certbot_script }} certonly --standalone --expand --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
certbot_certs: 
  - email: lg@lgaggini.net
    domains:
    - nibiru.lgaggini.net
certbot_force_regenerate: false
certbot_create_standalone_stop_services:
  - nginx
