---
node_exporter_version: 0.18.1
node_exporter_web_listen_address: "127.0.0.1:9100"

node_exporter_system_group: "node-exp"
node_exporter_system_user: "{{ node_exporter_system_group }}"

node_exporter_textfile_dir: "/var/lib/node_exporter"

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"

node_exporter_disabled_collectors: []
