---
- name: motd | install custom issue.net
  copy: src=issue.net dest=/etc/issue.net owner=root group=root mode=0644

- name: motd | install custom figlet font for motd
  copy: src=basic.flf dest=/usr/share/figlet/basic.flf owner=root group=root mode=0644

- name: motd | retrieve custom motd
  git: repo=https://github.com/lgaggini/update-motd.git dest=/tmp/update-motd

- name: motd | install custom motd
  synchronize: src=/tmp/update-motd/update-motd.d/ dest=/etc/update-motd.d
  delegate_to: "{{ inventory_hostname }}"
